README.md, manuals/InfluenceFunctions.md, plugins/_Post_Process/_XAI/influence_functions.py, plugins/_Post_Process/_XAI/influence_functions/__init__.py, plugins/_Post_Process/_XAI/influence_functions/infl.py, plugins/_Post_Process/_XAI/sgd_influence/args.py, plugins/_Post_Process/_XAI/sgd_influence/eval.py, plugins/_Post_Process/_XAI/sgd_influence/infl.py, plugins/_Post_Process/_XAI/sgd_influence/model.py, plugins/_Post_Process/_XAI/sgd_influence/train.py
This is a plugin of influence functions.
=> [XAI]add files for influnce functions

manuals/SHAP.md, plugins/_Post_Process/_XAI/shap_batch_tabular.py, plugins/_Post_Process/_XAI/shap_tabular.py, plugins/_Post_Process/_XAI/shap_tabular/__init__.py, plugins/_Post_Process/_XAI/shap_tabular/calculate.py, plugins/_Post_Process/_XAI/shap_tabular/visualize.py
This is a plugin kernel shap for tabular data.
=> [XAI] add files for kernel shap (tabular)

plugins/_Post_Process/_XAI/tracin/calculate_score.py, plugins/_Post_Process/_XAI/utils/file.py
Add column(y label) to output csv file.
=> fix tracin output format

manuals/SGDinfl.md, plugins/_Post_Process/_XAI/sgd_influence_tabular.py, plugins/_Post_Process/_XAI/sgd_influence_tabular/args.py, plugins/_Post_Process/_XAI/sgd_influence_tabular/eval.py, plugins/_Post_Process/_XAI/sgd_influence_tabular/infl.py, plugins/_Post_Process/_XAI/sgd_influence_tabular/network.py, plugins/_Post_Process/_XAI/sgd_influence_tabular/train.py
This is a bug fix for SGD influence tabular version of Neural Network Console plugin.
=> [XAI] Fix sgd influence tabular

plugins/_Post_Process/_XAI/gradcam_batch.py, plugins/_Post_Process/_XAI/lime_batch.py, plugins/_Post_Process/_XAI/shap_batch.py, plugins/_Post_Process/_XAI/utils/file.py
This is a fix to show the XAI results near the original data for batch version.
=> [XAI] fix image path order in output csv file

plugins/_Post_Process/_XAI/gradcam_utils/setup_model.py
This is an update for Grad-CAM plugin to raise error when no convolution layer is in model.
=> [XAI] stop process when no convolution layer is found (GradCAM) 

manuals/Post_Process/XAI/TracIn.rst, plugins/_Post_Process/_XAI/tracin_influence.py, plugins/_Post_Process/_XAI/tracin_utils/args.py, plugins/_Post_Process/_XAI/tracin_utils/calculate_score.py, plugins/_Post_Process/_XAI/tracin_utils/datasource.py
This is a new plugin of Tracin for nnc.
This plugin can be executed following the default training project of nnc by loading nnp files of model.
=> [XAI] TracIn plugin Update

.github/workflows/check_and_tests.yml, tools/scripts/copyright_checker.py
Corrected because the tool for checking copyright notation was not compatible in 2022
=> Fix copyright checker

manuals/Post_Process/XAI/InfluenceFunctions.rst, manuals/Post_Process/XAI/SGDInfluence.rst, manuals/ja/Post_Process/XAI/InfluenceFunctions.rst, manuals/ja/Post_Process/XAI/SGDInfluence.rst, plugins/_Post_Process/_XAI/SGD_influence.py, plugins/_Post_Process/_XAI/influence_functions.py, plugins/_Post_Process/_XAI/sgd_influence_utils/args.py, plugins/_Post_Process/_XAI/sgd_influence_utils/model.py, plugins/_Post_Process/_XAI/sgd_influence_utils/utils.py
This is a change to calculate the mean value from influence scores with different seeds.
=> [XAI] Feature/20211122 xai sgd influence mean val 

plugins/_Pre_Process/_Download_or_Generate_Dataset/create_20newsgroups_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_adult_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_character_extraction_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_cifar100_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_cifar10_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_fashion_mnist_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_flower_food_sr_dataset.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_german_credit_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_mnist_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_mnist_cyclegan_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_object_detection_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_object_detection_csv_for_centernet.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_pascal_voc_2012_segmentation_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_pascal_voc_2012_single_object_detection_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_sin_wave_anomaly_detection_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_wav_keyboard_sound_csv.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/create_wav_keyboard_sound_nr_dataset.py, plugins/_Pre_Process/_Download_or_Generate_Dataset/object_detection_utils/create_object_detection_yolov2.py
This PR supports plugins for dataset download scripts.
=> Added download or generate plugins

manuals/Post_Process/XAI/XAI_Visualization.rst, manuals/ja/Post_Process/XAI/XAI_Visualization.rst, plugins/_Post_Process/_XAI/gradcam.py, plugins/_Post_Process/_XAI/gradcam_batch.py, plugins/_Post_Process/_XAI/gradcam_utils/gradcam_func.py, plugins/_Post_Process/_XAI/lime.py, plugins/_Post_Process/_XAI/lime_batch.py, plugins/_Post_Process/_XAI/lime_utils/lime_func.py, plugins/_Post_Process/_XAI/shap.py, plugins/_Post_Process/_XAI/shap_batch.py, plugins/_Post_Process/_XAI/shap_utils/shap_func.py, plugins/_Post_Process/_XAI/smoothgrad.py, plugins/_Post_Process/_XAI/smoothgrad_batch.py, plugins/_Post_Process/_XAI/smoothgrad_utils/smoothgrad_func.py, plugins/_Post_Process/_XAI/xai_visualization.py, plugins/_Post_Process/_XAI/xai_visualization_batch.py
This is a plugin that is XAI visulalization by Grad-CAM, SHAP, LIME, and Smooth Grad.
=> [XAI] XAI Visualization (GradCAM, SHAP, LIME, SmoothGrad) 

manuals/Post_Process/XAI/AttentionMapVisualization.rst, manuals/ja/Post_Process/XAI/AttentionMapVisualization.rst, plugins/_Post_Process/_XAI/abn_attention_map.py, plugins/_Post_Process/_XAI/abn_utils/__init__.py, plugins/_Post_Process/_XAI/abn_utils/abn.py, plugins/_Post_Process/_XAI/abn_utils/args.py, plugins/_Post_Process/_XAI/utils/image.py, plugins/_Post_Process/_XAI/utils/model.py
This is a plugin for attention map visulalization.
=> [XAI]improve abn attention map

manuals/Post_Process/Utils/FeatureVisualization.rst, plugins/_Post_Process/_Utils/feature_visualization.py, plugins/_Post_Process/_Utils/feature_visualization_batch.py
Added Feature Visualization plugins.
学習済みモデルの任意の中間層出力を可視化するプラグインです。
処理対象データが単一のものと、データセット全体のもの、2つのバージョンを用意しています。
=> feature visualization

README.md, manuals/Post_Process/XAI/AttentionMapVisualization.rst, manuals/ja/Post_Process/XAI/AttentionMapVisualization.rst, plugins/_Post_Process/_XAI/abn_attention_map_batch.py
This is a pluing of attention map visualization with all validation data (batch).
=> [XAI]attention map visualization batch plugin

plugins/_Post_Process/_XAI/lime_tabular.py, plugins/_Post_Process/_XAI/lime_tabular_batch.py, plugins/_Post_Process/_XAI/shap_tabular.py, plugins/_Post_Process/_XAI/shap_tabular_batch.py
We resolved conflict on the pulgins on tabla data.
=> [XAI] fix conflicts of tabular plugins

README.md, README_ja.md, manuals/Post_Process/Fairness/Bias_Mitgation/reject_option_based_classification.rst, manuals/ja/Post_Process/Fairness/Bias_Mitgation/reject_option_based_classification.rst, plugins/_Post_Process/_Fairness/_Bias_Mitgation/reject_option_based_classification.py, plugins/_Post_Process/_Fairness/_Bias_Mitgation/reject_option_based_classification_predict.py, plugins/_Post_Process/_Fairness/_Bias_Mitgation/utils/utils.py
We have added Reject Option-Based Classification post-processing bias mitigation algorithm in Neural Network Console.
=> [Fairness] Reject Option-Based Classification NNC post-processing plugin

.github/workflows/check_and_tests.yml, plugins/_Post_Process/_XAI/lime_tabular.py, tools/scripts/check_plugin_help.py
=> Follow newest autopep8 rule, and fix numpy version to check help

README.md, README_ja.md
=> Fix conflicts on README

plugins/_Post_Process/_XAI/_Table/sgd_influence_tabular.py, tools/scripts/check_plugin_help.py
This is bugfix. We updated the plugin checker and fix sgd_influence_tabular.
=> [XAI] Update plugin checker and fix sgd_influence_tabular

manuals/Post_Process/XAI/LIME.rst, plugins/_Post_Process/_XAI/_Table/lime_tabular.py, plugins/_Post_Process/_XAI/_Table/lime_tabular_batch.py, plugins/_Post_Process/_XAI/_Table/shap_tabular.py, plugins/_Post_Process/_XAI/_Table/shap_tabular_batch.py
Here, updated the lime and shap plugins & updated manual for LIME.rst. The changes made are,
In lime_tabular.py:
Removed the categorical variables.
Extracted only the features column from the csv.
Created copy of data from sample data.
Included Softmax function(We need the prediction probabilities).
Minor change in kernel function.
For ease of understanding, we modified the feature names.
Created plot for visualization of LIME importance.
In lime_tabular_batch.py:
Removed the categorical variables.
Extracted only the features column from the csv.
Created copy of data from sample data.
Included Softmax function(We need the prediction probabilities).
Minor change in kernel function.
Created plot for visualization of LIME importance with two plots - Mean weight plot and Beeswarm plot.
In …
=> [Fairness]NNC plugins Bug fix and verification 

plugins/_Post_Process/_Visualization/precision_recall_curve.py, plugins/_Post_Process/_Visualization/roc_auc.py
Here we have updated the help statement in roc curve plugin and pr curve plugin.
=> [Fairness] ROC curve and PR curve

manuals/Post_Process/XAI/GradCAM.rst, plugins/_Post_Process/_XAI/_Image/gradcam.py, plugins/_Post_Process/_XAI/_Image/gradcam_batch.py, plugins/_Post_Process/_XAI/_Image/gradcam_utils/setup_model.py
We have updated the two Grad-CAM plugins that support for both single and multiple output model and modified the manual GradCAM.rst.
=> [Fairness] Grad-CAM NNC plugins

plugins/_Post_Process/_XAI/_Image/lime_utils/lime_func.py, plugins/_Post_Process/_XAI/_Image/tracin_utils/args.py, plugins/_Post_Process/_XAI/_Table/lime_tabular.py, plugins/_Post_Process/_XAI/_Table/lime_tabular_batch.py, plugins/_Post_Process/_XAI/_Table/sgd_influence_tabular_utils/args.py, plugins/_Post_Process/_XAI/_Table/shap_tabular.py, plugins/_Post_Process/_XAI/_Table/shap_tabular_batch.py
We have fixed the following issues,
- Plugin names updated for XAI->Table.
- Fixed the issue caused by updated skimage package, so modified the LIME image for single data plugin.
- Included the model path for XAI->Image->TracIn (all data) plugin.
=> [Fairness] Plugin issues fixed 

plugins/_Post_Process/_XAI/_Table/lime_tabular_batch.py
We have fixed the following issues,
* Included conflicts in LIME plugins
=> [XAI] fix conflicts of LIME plugins

.github/workflows/check_and_tests.yml, plugins/_Training/clip_zero_shot_image_classification.py, plugins/_Training/padim.py, plugins/_Training/padim_c1.py, plugins/_Training/patchcore.py, plugins/_Training/transfer_learning_c1.py, plugins/_Training/transfer_learning_imagenet.py, plugins/_Training/transfer_learning_vit.py
=> add Clip, PaDiM, PatchCore and Transferlearning plugins

plugins/_AISolutions/_ChatGPT/chatgpt.py, plugins/_AISolutions/_ChatGPT/templates/home.html
Fixed an issue that didn't work due to ChatGPT interface change.
=> Fixed error and updated default model

plugins/_Training/patchcore_c1.py
This is same patchcore as NNC-Cloud's.
=> add patchcore plugin

plugins/_Pre_Process/_Create_Dataset/simple_text_classification.py
There was an issue when downloading 20newsgroup dataset.
This PR fixes the `Resource punkt_tab not found.` issue.
=> fixed punkt_tab not found issue
